name: CI
concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  # # Triggers the workflow on push but only for the main branches
  push:
    branches:
      - master
      - develop
      - anti-gps-spoofing
    paths-ignore:
      - "**.md"
      - version.properties

  # Note: This is different from "pull_request". Need to specify ref when doing checkouts.
  pull_request_target:
    branches:
      - master
      - develop
      - anti-gps-spoofing
    paths-ignore:
      - "**.md"
      #- "**.yml"

  workflow_dispatch:

jobs:
  setup:
    strategy:
      fail-fast: true
      matrix:
        arch:
          - all
          - check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: pip
      - run: pip install -U platformio
      - name: Generate matrix
        id: jsonStep
        run: |
          if [[ "$GITHUB_HEAD_REF" == "" ]]; then
            TARGETS=$(./bin/generate_ci_matrix.py ${{matrix.arch}})
          else  
            TARGETS=$(./bin/generate_ci_matrix.py ${{matrix.arch}} --level pr)
          fi
          echo "Name: $GITHUB_REF_NAME Base: $GITHUB_BASE_REF Ref: $GITHUB_REF"
          echo "${{matrix.arch}}=$TARGETS" >> $GITHUB_OUTPUT
          echo "$TARGETS" >> $GITHUB_STEP_SUMMARY
    outputs:
      all: ${{ steps.jsonStep.outputs.all }}
      check: ${{ steps.jsonStep.outputs.check }}

  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get release version string
        run: |
          echo "long=$(./bin/buildinfo.py long)" >> $GITHUB_OUTPUT
          echo "deb=$(./bin/buildinfo.py deb)" >> $GITHUB_OUTPUT
        id: version
        env:
          BUILD_LOCATION: local
    outputs:
      long: ${{ steps.version.outputs.long }}
      deb: ${{ steps.version.outputs.deb }}

  check:
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        check: ${{ fromJson(needs.setup.outputs.check) }}
    # Use 'arctastic' self-hosted runner pool when checking in the main repo
    runs-on: ${{ github.repository_owner == 'meshtastic' && 'arctastic' || 'ubuntu-latest' }}
    if: ${{ github.event_name != 'workflow_dispatch' && github.repository == 'glebchek/meshtastic-anti-gps-spoofing' }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Check ${{ matrix.check.board }}
        uses: meshtastic/gh-action-firmware@main
        with:
          pio_platform: ${{ matrix.check.platform }}
          pio_env: ${{ matrix.check.board }}
          pio_target: check

  build:
    needs: [setup, version]
    strategy:
      fail-fast: false
      matrix:
        build: ${{ fromJson(needs.setup.outputs.all) }}
    uses: ./.github/workflows/build_firmware.yml
    with:
      version: ${{ needs.version.outputs.long }}
      pio_env: ${{ matrix.build.board }}
      platform: ${{ matrix.build.platform }}

  test-native:
    if: github.repository == 'glebchek/meshtastic-anti-gps-spoofing'
    uses: ./.github/workflows/test_native.yml

  gather-artifacts:
    # trunk-ignore(checkov/CKV2_GHA_1)
    if: github.repository == 'glebchek/meshtastic-anti-gps-spoofing'
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        arch:
          - esp32
          - esp32s3
          - esp32c3
          - esp32c6
          - nrf52840
          - rp2040
          - rp2350
          - stm32
    runs-on: ubuntu-latest
    needs: [version, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - uses: actions/download-artifact@v7
        with:
          path: ./
          pattern: firmware-${{matrix.arch}}-*
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R

      - name: Repackage in single firmware zip
        uses: actions/upload-artifact@v6
        with:
          name: firmware-${{matrix.arch}}-${{ needs.version.outputs.long }}
          overwrite: true
          path: |
            ./firmware-*.mt.json
            ./firmware-*.bin
            ./firmware-*.uf2
            ./firmware-*.hex
            ./firmware-*.zip
            ./device-*.sh
            ./device-*.bat
            ./littlefs-*.bin
            ./bleota*bin
            ./mt-*-ota.bin
            ./Meshtastic_nRF52_factory_erase*.uf2
          retention-days: 30

      - uses: actions/download-artifact@v7
        with:
          name: firmware-${{matrix.arch}}-${{ needs.version.outputs.long }}
          merge-multiple: true
          path: ./output

      # For diagnostics
      - name: Show artifacts
        run: ls -lR

      - name: Device scripts permissions
        run: |
          chmod +x ./output/device-install.sh || true
          chmod +x ./output/device-update.sh || true

      - name: Zip firmware
        run: zip -j -9 -r ./firmware-${{matrix.arch}}-${{ needs.version.outputs.long }}.zip ./output

      - name: Repackage in single elfs zip
        uses: actions/upload-artifact@v6
        with:
          name: debug-elfs-${{matrix.arch}}-${{ needs.version.outputs.long }}
          overwrite: true
          path: ./*.elf
          retention-days: 30

      - uses: scruplelesswizard/comment-artifact@main
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: firmware-${{matrix.arch}}-${{ needs.version.outputs.long }}
          description: "Download firmware-${{matrix.arch}}-${{ needs.version.outputs.long }}.zip. This artifact will be available for 90 days from creation"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  release-artifacts:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.repository == 'glebchek/meshtastic-anti-gps-spoofing' }}
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    needs:
      - setup
      - version
      - gather-artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Generate release notes
        id: release_notes
        run: |
          chmod +x ./bin/generate_release_notes.py
          NOTES=$(./bin/generate_release_notes.py ${{ needs.version.outputs.long }})
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          draft: true
          prerelease: true
          name: Meshtastic Firmware ${{ needs.version.outputs.long }} Alpha
          tag_name: v${{ needs.version.outputs.long }}
          body: ${{ steps.release_notes.outputs.notes }}

      - name: Generate Release manifest
        run: |
          jq -n --arg ver "${{ needs.version.outputs.long }}" --argjson targets ${{ toJson(needs.setup.outputs.all) }} '{
            "version": $ver,
            "targets": $targets
          }' > firmware-${{ needs.version.outputs.long }}.json

      - name: Save Release manifest artifact
        uses: actions/upload-artifact@v6
        with:
          name: manifest-${{ needs.version.outputs.long }}
          overwrite: true
          path: firmware-${{ needs.version.outputs.long }}.json

      - name: Add manifest to GitHub Release
        run: |
          gh release upload v${{ needs.version.outputs.long }} ./firmware-${{ needs.version.outputs.long }}.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-firmware:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - esp32
          - esp32s3
          - esp32c3
          - esp32c6
          - nrf52840
          - rp2040
          - rp2350
          - stm32
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.repository == 'glebchek/meshtastic-anti-gps-spoofing'}}
    needs: [release-artifacts, version]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - uses: actions/download-artifact@v7
        with:
          pattern: firmware-${{matrix.arch}}-${{ needs.version.outputs.long }}
          merge-multiple: true
          path: ./output

      - name: Display structure of downloaded files
        run: ls -lR

      - name: Device scripts permissions
        run: |
          chmod +x ./output/device-install.sh || true
          chmod +x ./output/device-update.sh || true

      - name: Zip firmware
        run: zip -j -9 -r ./firmware-${{matrix.arch}}-${{ needs.version.outputs.long }}.zip ./output

      - uses: actions/download-artifact@v7
        with:
          name: debug-elfs-${{matrix.arch}}-${{ needs.version.outputs.long }}
          merge-multiple: true
          path: ./elfs

      - name: Zip debug elfs
        run: zip -j -9 -r ./debug-elfs-${{matrix.arch}}-${{ needs.version.outputs.long }}.zip ./elfs

      # For diagnostics
      - name: Display structure of downloaded files
        run: ls -lR

      - name: Add bins and debug elfs to GitHub Release
        run: |
          gh release upload v${{ needs.version.outputs.long }} ./firmware-${{matrix.arch}}-${{ needs.version.outputs.long }}.zip
          gh release upload v${{ needs.version.outputs.long }} ./debug-elfs-${{matrix.arch}}-${{ needs.version.outputs.long }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

